//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS_API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PMSEntities : DbContext
    {
        public PMSEntities()
            : base("name=PMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<Architect> Architects { get; set; }
        public virtual DbSet<AutocadDiagram> AutocadDiagrams { get; set; }
        public virtual DbSet<BusinessPartner> BusinessPartners { get; set; }
        public virtual DbSet<Checklist> Checklists { get; set; }
        public virtual DbSet<FixingType> FixingTypes { get; set; }
        public virtual DbSet<NewProject> NewProjects { get; set; }
        public virtual DbSet<Owner> Owners { get; set; }
        public virtual DbSet<ProjectHealth> ProjectHealths { get; set; }
        public virtual DbSet<ProjectPicture> ProjectPictures { get; set; }
        public virtual DbSet<ProjectStatu> ProjectStatus { get; set; }
        public virtual DbSet<ProjectType> ProjectTypes { get; set; }
        public virtual DbSet<VisitReport> VisitReports { get; set; }
    }
}
