//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewProject
    {
        public NewProject()
        {
            this.AutocadDiagrams = new HashSet<AutocadDiagram>();
            this.VisitReports = new HashSet<VisitReport>();
        }
    
        public int Id { get; set; }
        public string ProjectName { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public string CommencedOn { get; set; }
        public string ConcludedOn { get; set; }
        public int ArchitectId { get; set; }
        public int BusinessPartnerId { get; set; }
        public string PlanUrl { get; set; }
        public string SectionsUrl { get; set; }
        public string ElevationsUrl { get; set; }
        public string TDImageUrl { get; set; }
        public string AreaPanelCalculationUrl { get; set; }
        public string ConceptsDrawingUrl { get; set; }
        public string OptimizationUrl { get; set; }
        public string ShopDrawingUrl { get; set; }
        public string AnalysisUrl { get; set; }
        public string BOQUrl { get; set; }
        public string InteriorUrl { get; set; }
        public int OwnerId { get; set; }
        public int ProjectTypeId { get; set; }
        public int FixingTypeId { get; set; }
        public int ApplicationsId { get; set; }
        public string TDRenderImageUrl { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual Architect Architect { get; set; }
        public virtual ICollection<AutocadDiagram> AutocadDiagrams { get; set; }
        public virtual BusinessPartner BusinessPartner { get; set; }
        public virtual FixingType FixingType { get; set; }
        public virtual ICollection<VisitReport> VisitReports { get; set; }
        public virtual Owner Owner { get; set; }
        public virtual ProjectType ProjectType { get; set; }
    }
}
